trainingInput:
  hyperparameters:
    hyperparameterMetricTag: accuracy
    goal: MAXIMIZE
    maxTrials: 4
    maxParallelTrials: 2
    enableTrialEarlyStopping: True
    params:
    - parameterName: batch_size
      type: INTEGER
      minValue: 8
      maxValue: 512
      scaleType: UNIT_LOG_SCALE
    - parameterName: dnn_lr
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.5
      scaleType: UNIT_LOG_SCALE
    - parameterName: lin_lr
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.5
      scaleType: UNIT_LOG_SCALE
    - parameterName: lin_lr_power
      type: DOUBLE
      minValue: -5
      maxValue: 0.0
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: lin_l1
      type: DOUBLE
      minValue: 0.01
      maxValue: 100
      scaleType: UNIT_LOG_SCALE
    - parameterName: lin_l2
      type: DOUBLE
      minValue: 0.01
      maxValue: 100
      scaleType: UNIT_LOG_SCALE
    - parameterName: lin_shrinkage
      type: DOUBLE
      minValue: 0.00001
      maxValue: 100
      s
