project_id: "cchatterjee-sandbox"
bucket_id: "cchatterjee-sandbox"
model:
    name: "demo_model"
    path: "examples.sklearn.sklearn_model"
args:
    - name: "model_dir"
      help: "Dir or bucket to save model files."
      default: "models"
