# Config file for AI Pipeline.

project_id: [PROJECT ID]
bucket_id: [BUCKET ID]
region: "us-central1"
scale_tier: "STANDARD_1"
runtime_version: "1.15"
python_version: "3.7"
model:
    name: "smh_xgb_demo_v1"
    path: "examples.xgboost.xgboost_model"
hyperparameter:
    directory: "examples/xgboost/hptuning_config.yaml"
